In [5]:
import oakvar as ov

You will need to `pip install connectorx == 0.3.2`

In [6]:
df = ov.get_df_from_db('exampleinput.sqlite').to_pandas()

In [13]:
df.iloc[:,:10]

,base__uid,base__chrom,base__pos,base__pos_end,base__ref_base,base__alt_base,base__tags,base__coding,base__hugo,base__transcript
0,1,chr10,121593817,121593817,T,A,None,Y,FGFR2,ENST00000358487.10
1,2,chr10,2987654,2987654,T,A,None,None,None,None
2,3,chr10,43077259,43077259,A,T,None,Y,RET,ENST00000355710.8
3,4,chr10,8055656,8055656,A,T,None,Y,GATA3,ENST00000379328.9
4,5,chr10,87864470,87864470,A,T,None,Y,PTEN,ENST00000371953.8
...,...,...,...,...,...,...,...,...,...,...
368,369,chrX,64193286,64193286,T,A,None,Y,AMER1,ENST00000374869.8
369,370,chrX,67545147,67545147,A,T,None,Y,AR,ENST00000374690.9
370,371,chrX,71120077,71120077,A,T,None,Y,MED12,ENST00000374080.8
371,372,chrX,77786001,77786001,T,A,None,Y,ATRX,ENST00000373344.11
372,373,chrY,13479665,13479665,T,A,None,Y,UTY,ENST00000545955.6

In [14]:
df.iloc[:,10:]

,base__so,base__cchange,base__achange,base__exonno,base__all_mappings,base__refseq,clinvar__sig,clinvar__disease_refs,clinvar__disease_names,clinvar__rev_stat,...,clinvar__sig_conf,original_input__chrom,original_input__pos,original_input__pos_end,original_input__ref_base,original_input__alt_base,tagsampler__genotypes,tagsampler__numsample,tagsampler__samples,tagsampler__tags
0,MLO,c.1A>T,p.Met1?,2.0,"{""FGFR2"": [[""P21802"", ""p.Met1?"", ""MIS,MLO"", ""E...",NM_000141,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s0,
1,None,None,None,NaN,{},None,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s1,
2,MLO,c.1A>T,p.Met1?,1.0,"{""RET"": [[""P07949"", ""p.Met1?"", ""MIS,MLO"", ""ENS...",NM_020975,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s2,
3,MLO,c.1A>T,p.Met1?,2.0,"{""GATA3"": [[""P23771"", ""p.Met1?"", ""MIS,MLO"", ""E...",NM_001002295,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s3,
4,MLO,c.1A>T,p.Met1?,1.0,"{""ENSG00000289051"": [[""C0HLV8"", """", ""2KD"", ""EN...",NM_000314,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s4,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,MLO,c.1A>T,p.Met1?,2.0,"{""AMER1"": [[""Q5JTC6"", ""p.Met1?"", ""MIS,MLO"", ""E...",NM_152424,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s3,
369,MLO,c.1A>T,p.Met1?,1.0,"{""AR"": [[""P10275"", ""p.Met1?"", ""MIS,MLO"", ""ENST...",NM_000044,Likely pathogenic,"MONDO:MONDO:0010735,MedGen:C1839259,OMIM:31320...",Kennedy disease|Androgen resistance syndrome,"criteria provided, single submitter",...,None,None,NaN,NaN,None,None,,1,s4,
370,MIS,c.460A>T,p.Met154Leu,4.0,"{""MED12"": [[""A0A0A0MR79"", ""p.Met154Leu"", ""MIS""...",NM_005120,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s0,
371,MLO,c.1A>T,p.Met1?,1.0,"{""ATRX"": [[""P46100"", ""p.Met1?"", ""MIS,MLO"", ""EN...",NM_000489,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s1,
372,MLO,c.1A>T,p.Met1?,1.0,"{""UTY"": [[""O14607"", ""p.Met1?"", ""MIS,MLO"", ""ENS...",NM_001258249,None,None,None,None,...,None,None,NaN,NaN,None,None,,1,s2,